- name: change-password-loop
  hosts: all
  become: true

  vars:
    new_password: "1234567"

  tasks:
    - name: Set new password for user
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ new_password | password_hash('sha512') }}"
      loop:
        - test
        - testt
