---
- name: Change DNS address of Linux clients
  hosts: all
  become: true

  tasks:
    - name: Update DNS configuration file
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 1.1.1.1'   # Replace with the desired DNS address.
      notify: Restart Network Service

  handlers:
    - name: Restart Network Service
      service:
        name: network
        state: restarted
