- name: change-password
  hosts: all
  become: true
  vars:
    user: "test"
    password: "1234567"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ user }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
