---
- name: Download Remote URL File
  hosts: all
  become: true

  tasks:
    - name: Download file
      ansible.builtin.get_url:
        url: "https://<site-domain-name>/logo.png"
        dest: "/home/<user>/logo.png"
