---
- name: Download Remote URL File
  hosts: all
  become: true

  tasks:
    - name: Download file
      ansible.builtin.get_url:
        url: "https://cdn.you.com/img/shared/logos/ydc-logo.svg"
        dest: "/home/sedat/logo.svg"
